import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import AuthSession from "@/app/_component/AuthSession";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
